### ISSUE TITLE
Fix image retrieval script to get each image in tweet with multiple images

### ISSUE THREAD

**Issue by IanMagnusson** [MangeFre/IITUDND#27]

**Comment by MangeFre** [comment]
I'm going to close this, because the script already does this! If not, we need to see what it is that doesn't work. 

If you want to see the code, there is a for-loop that runs from 0 to len(listofmedia) and downloads each image. The name of the images will be the tweet_id + user_id + the value of j, seperated by underscores.

**Comment by IanMagnusson** [comment]
Sorry I should have described this better in the issue comment. The problem is that the script uses ‘entities’ when it should use ‘extended_entities’ and this causes the inner loop to only run once no matter how many images are on the tweet. I don’t really know what the purpose of this part of the JSON is but ‘entities’ only ever contains the first media in a tweet (ie **not all of the photos.**) Stupid design on twitter’s part IMO.

**Comment by MangeFre** [comment]
Oh, I see, thanks for the quick correction!

Fixed it in the code and am running Maria now, will see if it seems to be working once I'm done. If so, I'll push my changes.

**Comment by MangeFre** [comment]
Fixed, tested and pushed!
